# redis-server.yml
version: '3.7'
services:
  was:
    container_name: was
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${SPRING_PORT}:3000"
    networks:
      - my-bridge-network
      - default 
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - my-bridge-network
  mysql:
    image: mysql:8.3
    container_name: rdbms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysupersecret
      MYSQL_DATABASE: file_share
      MYSQL_USER: testuser
      MYSQL_PASSWORD: verysupersecret
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-bridge-network


networks:
  my-bridge-network:
    driver: bridge

  